apiVersion: v1
kind: ImageStream
metadata:
  name: jdg7-trace
spec:
  tags:
    - name: '1.0'
      annotations:
        version: '1.0'
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/jboss-datagrid-7/datagrid71-openshift:1.2'